GET http://localhost:4000/auth/findProfile/627e9661b75ae40f1e8cf7a9

###

DELETE http://localhost:4000/posts/deleteComment
Content-Type: application/json

{
    "commentId":"628a63ccc094843dbb27c6a4"
}