### get profile

GET http://localhost:4000/auth/findProfile/627e9661b75ae40f1e8cf7a9

### delete comment

DELETE http://localhost:4000/posts/deleteComment
Content-Type: application/json

{
    "commentId":"628a63ccc094843dbb27c6a4"
}

### get comments

GET http://localhost:4000/posts/getComments/627e973bb75ae40f1e8cf7c0&15
Content-Type: application/json

### get comments for specific user
GET http://localhost:4000/posts/getUserComments/627e9661b75ae40f1e8cf7a9&0
Content-Type: application/json

### get posts (index & id) => (0&627e9661b75ae40f1e8cf7a9) or (0&all)

GET http://localhost:4000/posts/getPosts/0&627e9661b75ae40f1e8cf7a9
Content-Type: application/json

### get posts by tag => (tag) e.g (javascript)

GET http://localhost:4000/posts/getPostsByTag/JavaScript,Python
Content-Type: application/json


### get post by id

GET http://localhost:4000/posts/getPost/627e9797b75ae40f1e8cf7ce
Content-Type: application/json